apiVersion: v1
kind: Namespace
metadata:
  name: tas-adapter-install
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: tas-selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tas-selfsigned-ca
  namespace: tas-adapter-install
spec:
  isCA: true
  commonName: tas-selfsigned-ca
  secretName: root-secret # Change to something that makes more sense
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: tas-selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: tas-ca-issuer
  namespace: tas-adapter-install
spec:
  ca:
    secretName: root-secret # Change to something that makes more sense