apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaimPolicy
metadata:
  name: mysql-cross-namespace
  namespace: service-instances
spec:
  consumingNamespaces:
  - '*' # consumable from all namespaces
  subject:
    group: with.sql.tanzu.vmware.com
    kind: MySQL