---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tanzu-packages-contour
  namespace: flux-system
spec:
  dependsOn:
    - name: tanzu-packages-cert-manager
  interval: 5m0s
  path: ./contour
  prune: true
  sourceRef:
    kind: GitRepository
    name: tanzu-packages

