---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tanzu-packages-pre-reqs
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./pre-reqs
  prune: true
  sourceRef:
    kind: GitRepository
    name: tanzu-packages

