---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tanzu-packages-tas
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./tas-adapter
  prune: true
  sourceRef:
    kind: GitRepository
    name: tanzu-packages
  decryption:
    provider: sops
    secretRef:
      name: sops-key

