---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tanzu-packages-harbor
  namespace: flux-system
spec:
  dependsOn:
    - name: tanzu-packages-contour
  interval: 5m0s
  path: ./harbor
  prune: true
  sourceRef:
    kind: GitRepository
    name: tanzu-packages

