# apiVersion: v1
# kind: Namespace
# metadata:
#   name: grafana
#   labels: 
#     name: grafana
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    # tkg.tanzu.vmware.com/tanzu-package-ClusterRole: grafana-packages-cluster-role
    # tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: grafana-packages-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-Secret: grafana-packages-values
    # tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: grafana-packages-sa
  name: grafana
  namespace: tanzu-package-repo-global
spec:
  packageRef:
    refName: grafana.tanzu.vmware.com
    versionSelection:
      constraints: 7.5.7+vmware.2-tkg.1
  serviceAccountName: grafana-packages-sa
  values:
  - secretRef:
      name: grafana-packages-values
