---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
- contour-package-install.yaml
# - contour-sa.yaml
- contour-data-values-secret.yaml

# - git-secret.sops.yaml 
