apiVersion: v1
kind: Namespace
metadata:
    name: tas-adapter-install
    labels:
        name: tas-adapter-install
---
apiVersion: v1
data:
    .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS50YW56dS52bXdhcmUuY29tIjp7InVzZXJuYW1lIjoiYWlsZ2VuZnJpdHpAdm13YXJlLmNvbSIsInBhc3N3b3JkIjoiVHJvbWJvbmUwNiEhIn19fQ==
kind: Secret
metadata:
    name: tanzunet-registry
    namespace: tas-adapter-install
type: kubernetes.io/dockerconfigjson
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
    name: tanzunet-registry
    namespace: tas-adapter-install
spec:
    toNamespaces:
        - '*'
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
    annotations:
        tanzu.vmware.com/owner: tkg
    name: tas-adapter-repository
    namespace: tas-adapter-install
spec:
    fetch:
        imgpkgBundle:
            image: registry.tanzu.vmware.com/app-service-adapter/tas-adapter-package-repo:0.9.0
            secretRef:
                name: tanzunet-registry
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
    annotations:
        tkg.tanzu.vmware.com/tanzu-package-ClusterRole: tas-packages-cluster-role
        tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: tas-packages-cluster-rolebinding
        tkg.tanzu.vmware.com/tanzu-package-Secret: tas-packages-values
        tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: tas-packages-sa
    name: tas
    namespace: tas-adapter-install
spec:
    serviceAccountName: tas-packages-sa
    packageRef:
        refName: application-service-adapter.tanzu.vmware.com
        versionSelection:
            constraints: 0.9.0
    values:
        - secretRef:
            name: tas-packages-values
