---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
- tas-package-install.yaml
- tas-sa.yaml
# - git-secret.sops.yaml 
secretGenerator:
- name: tas-packages-values
  namespace: tas-adapter-install
  files:
  - tas-adapter-values.sops.yaml
  type: Opaque
  options:
    annotations:
      tkg.tanzu.vmware.com/tanzu-package: tas-packages