#ENC[AES256_GCM,data:bxGGxTsMPcJjgfQmFnS8lSyu00Mkxks8n3c+aIag9p5p0+WDMgEgnN1Z0/6HDKQo0pC/OnR346UDlOxj,iv:CvrpiELTunOe9YNsWLBDdqhUxwKzlyLRjlgeDaRlVDc=,tag:tOwMTsi4oGwxwoZ+/mdM9g==,type:comment]
#ENC[AES256_GCM,data:plOTUY4WLLc/yxrylyKgR5WWrRC1w02CJm+7u7STZK/zcNhQrFQtnXuKsIIcfBx4PetsgWmCM9Xymj+FLw==,iv:CnainEIdQ77BUwW2bJvpj8KPImpNrfWOCxoSPGYaR6o=,tag:SR3qq5ZR3j8+rejWQzN4pA==,type:comment]
ceip_policy_disclosed: ENC[AES256_GCM,data:+RQf5g==,iv:IekEpBiQoNlv+9IhHIqL4EiJZOHwiyeD160SDSnmtMA=,tag:uC9LZI9xFYPTqvwAuJhefw==,type:bool]
api_ingress:
    fqdn: ENC[AES256_GCM,data:SLVBFCwW2tUPW0xUAM6ER/M97qVSq8pU,iv:/OPr4MiLKJtLyVYtoC/ufTAK8jn6T71QbdP+nLZnOp4=,tag:0MNMmfxony7SgCKz7pHAqA==,type:str]
    tls:
        secret_name: ENC[AES256_GCM,data:gKIN2k/kVQmjBVV8CBSaB1iwa6EE1BrSkHTOpA==,iv:/3KZmMbI5nEVRc8RTIXHVAxYxb0DEntezGWKEN0IIk0=,tag:b9giYpUeb2q+Y9r6RoXOHA==,type:str]
        namespace: ENC[AES256_GCM,data:2LjNWLk2rBdFdU60D3xi9+3UXQ==,iv:b5xR5PWDO3a56KYE1l2jT3zaMRcasZrvaZBpTr4XUzM=,tag:8uNx29EASql3kStc2inrSw==,type:str]
app_ingress:
    default_domain: ENC[AES256_GCM,data:juPfkB4YLzWvJD9bdOts0zw=,iv:py3YVZPKQf0qELNmhABhuMPq7bH79goigasE8wUepis=,tag:4DhBu1Ogp5rfTgp17etFSA==,type:str]
    tls:
        secret_name: ENC[AES256_GCM,data:PB3yzkMAD+4dCweSQAr/NuCJUfud,iv:kUsqpNw/m1ENT6lve24l1ZXmhF2HPeKJijLD7T/UI58=,tag:OuXsP/bx2qOq3Ly+MAhVlA==,type:str]
        namespace: ENC[AES256_GCM,data:2lL+8gmcY+1P315Ude9Q+xy6aA==,iv:T8S0oInqNFxWhrKMapflNrhfsyuBO9T2cqMdOdHfitM=,tag:vJq0SsNOV33Lrwno3Z1LTQ==,type:str]
app_registry:
    credentials:
        username: ENC[AES256_GCM,data:so+FVA==,iv:h1DM0iGnUiP5dWN6HLFAsYSpzF/g/jQM7Tm0qcjx1y4=,tag:KSihzA1RUeOHGu0S/OzZ8w==,type:str]
        password: ENC[AES256_GCM,data:QB1BGA==,iv:rK5eiyUA6MNXuww6NPVEWd82Ii5sbJYsfK4W78Guyh8=,tag:tSP8BJ/n+D9VP+2LJDs0mA==,type:str]
    hostname: ENC[AES256_GCM,data:9tZJiA==,iv:/Yjn8AxF1ToNWeXNFsPMw696fxX2+/s8bqXD5hkq9Vs=,tag:MT+vrWMyssgEw+7GI/X3yw==,type:str]
    path:
        droplets: ENC[AES256_GCM,data:gna0C0q3jG33ESNk8FN01de5U4S7gNEEEMy/zA==,iv:RC9Jy7+GejJFmaC8JiFSCy9SSiZQ+FOCszeaT6mEjAo=,tag:err96zxD3w2cWSlnHcs7Zw==,type:str]
        packages: ENC[AES256_GCM,data:uoUoYK/MA2+dsb/hx3dsDgjOWs552p6U/eRBhuA=,iv:6P8dF7wQ2wmJvoa3gmMfu3rMN61ZkrW/ZMWtcSlJEks=,tag:ZZaPnGDXY7H/MXQNkyhe8Q==,type:str]
        #ENC[AES256_GCM,data:8Bdu8aHlXzcY,iv:6f3XDGAOmoK1IwVrag31rjy0R8G0dCca0UJ4eoPWPu0=,tag:kjXbwpwVQ3kuPZlBltApiw==,type:comment]
        #ENC[AES256_GCM,data:5OB97YiVcj8jtw==,iv:b7zUODVQzp+MiWldJJPd+a7GapDdFTSYrBBnEJruwTg=,tag:U8/VCGAmy5u7FqlOKO/7vw==,type:comment]
        #ENC[AES256_GCM,data:7XDAZj910uQKl5CYHbJEe/g33CS2lCExY9EwNSyxEX70oVYQgQ==,iv:1e5SWADza7hLOqzTuvMJp9+/pGM7s1ha6OnxrkrZV4I=,tag:CNSfoPjo3yYzAHjk6GN8uA==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-03T13:01:44Z"
    mac: ENC[AES256_GCM,data:zRsWDCwExZA4/zdwchkTojYbWuxXw9YhfUetnPHTmxvdAoBnwwv57yAWEuYv7Z/lr6gIoKcQLpqefYJfriZ3uI37xmj8deWG9uxD/QreAFLnfxz2Svq6uRSyKUWqSeYB9OPDV05YhTI/hsBEIQ2+NZtvlXjHdnhg8Lmr/UBpsjY=,iv:8/NPnFJkyUtqEtNl8U/qEsQbcN3IPEmfRMMqlp2x8fE=,tag:11//umwhvGdGyIXCeq0Frw==,type:str]
    pgp:
        - created_at: "2022-11-03T13:01:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA3HlrFaHk7dsAQv/apCJ8o8W3PaH3P4mXb21vaaZr0U4DpOeX+FNDgkkwIO4
            ulIp9VxNfky/PlZa2dDVuqCB214LJU0dQDXzUmjcbT0sPB0U8Ek/Go3y08h2UmTp
            WWGH3nr4zJqDPm1cSKijsFMTrPadT0XYVeNhk8zf53iA1JC33lUOzt4zNoah0jmU
            3NEPWCuQkbLjNW7By8gVDRcjIK8PxVmeBEdn91LAu1nAHctW8oyRjpEdJ3ouEAhG
            G5TgYBoWVzs+UzvJkQDAFvTL/oKMsiRCINlu2bj85FZXYIHOR2ZEF7yqzkOYEzX5
            yLc8dbDRBi/O+oq0MZKbj5sW2BOZrgbzhgOVniIAEwPuRQ2W2avfgcCeFqFRPdPm
            iLlLevOYcwxTbfQqYrYnZZRsVcAnTFlEq9Dnl4tT1y4MH5GZTYL2mu96kEyPpLHn
            OuV5lJa5J8ZwmwI2bbsd6V66bIO7Kmtm6ZaTufkHqpYKavspn/+wOJmjLiEOGOuz
            2SpoDXIJmXTj2dk8KqEk0l4BMGARsJE/OuXHQuJtQAa1ZUHppFnhKn6xNNU/YMOs
            1LAP51hQCvLWSoT+8cvWtbGLGh6+cfB1MCMKvuGJj2Mb5C17ZYa6EMxLCCfzmjjK
            XMPQk0ceKLBODrXkVwy3
            =gXEF
            -----END PGP MESSAGE-----
          fp: FC27C16498EABECF5D4A8813C74A746154936D25
    unencrypted_suffix: _unencrypted
    version: 3.7.3
