---
# tas_adapter: you get some key value pair package failure...
  ceip_policy_disclosed: true # Installation fails if this is not set to true. Not a string.
  api_ingress:
    fqdn: "tas-adapter.kdash.vmware"
    tls:
      secret_name: tas-adapter.kdash.vmware-tls
      namespace: tas-adapter-install
  app_ingress:
    default_domain: "apps.kdash.vmware"
    tls:
      secret_name: apps.kdash.vmware-tls
      namespace: tas-adapter-install
  app_registry:
    credentials:
      username: "user"
      password: "pass"
    hostname: "host"
    path:
      droplets: "/tas-adapter/adapter-droplet"
      packages: "/tas-adapter/adapter-packages"
    # ca_cert:
    #   data: |
    #     PEM-ENCODED-CERTIFICATE-CONTENTS