apiVersion: ENC[AES256_GCM,data:Piw=,iv:vJi7ditWesRtw8Q+5HCcN7syPQ5S1xRoWdut27PFees=,tag:85LBURLQSt5tArP1+QNs4w==,type:str]
kind: ENC[AES256_GCM,data:7WyNSoeRS3wB,iv:MKfDg6o0NcAjs5/Ffgw2bfASgv8IVcJXOcpVJlZ1GbY=,tag:mEBKxofgaYVvNZVgT94/NQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:C6tQ+x5jKalzd9PaAIqlsg80kg==,iv:DK3TqFLQnZmuBRVQJShzGA1tI88bAIkeuGAwgS+rhmk=,tag:7yEW0eWx3+gb/nwuLgaKYg==,type:str]
    labels:
        name: ENC[AES256_GCM,data:WBMRe9Af2DI4uD8/9pJnsjPxZw==,iv:aRs8ZgCHMDufBi1tnGgVFo3LWT3bLMgb6eSYnEOqufs=,tag:S/4GdUu7KilTI/y+Cxfa3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-10-19T15:48:05Z"
    mac: ENC[AES256_GCM,data:Sx1qj5tYrWH0/PST1962SUAtyPK6hjJO4uSSNUBksdDI9Hm/k/x16+hrg7MHebEdDcnUHlopAbtvBmBgJn06VkkDBKWTBEAT4AM4inyv/S8nsg8RYIw72tkzelT6O//CkSlw3mTI1X3WbwX1Cv385D1AV0AsQS1VTsIKaSoj9CM=,iv:wpJiJ/LQtDdBUoEsnzo4oArTV74IvDsMdaoND52UZLc=,tag:y2TqpII+1DEe3WWg9QSu4g==,type:str]
    pgp:
        - created_at: "2022-10-18T21:00:30Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0FQ4OXZhO54AQ//R51F/hR6U2zxTvyRziasecAjx0yXKD4ntR8xlWonjY1V
            YP4xlnI1gUwZTnt4fyfYkz1Qn8XiKt6P+5ee7nFwgHQ/Ay85Xkmjjx8hNqQtPZVJ
            jtg/BBqbHcg0BbybYLnWKmNFt1cSLCRm4CUDLP02LtIP/h8GkI6zz/Mtri4SEVq1
            AAeufmvOjBfRGLcKiuUGA7gDCMOV4K7TL8wX1i0BR9Fbr6eXbS4DsHZ8l+Y8UGXh
            CYd4JUwdF9WQq2mK7XG7+evJdBqXJFJTl8F2VHL6i8vJLp4diU8TA9M91HJ4qrMW
            ky/CTOXrGTFWCutfch5xEtHE6KNuYBGL5l1nWOFt0ceDubSTROWY6Nfb+F9NWMZ+
            CyB+3QCV2I/bee71/aTxaYdMX7fyHuscSbKrCSA0k07UW850sMW3vie47NrohDwz
            XLUknotYtQ5EaC5dxtyOLCRnkFEpoQM97s/41C959R/vJOed/SId6lbCSer4HEGz
            4C90YG9b8V69zu92m+xo+jP7TxfqgkLcWnlQ2gCpzozgUCUX2waJD0dyIxnbIJez
            bxhs2LnXttyZ9oKoH8wFFS8teMpJ7L4YcqPewZYa92w9AvYQpImhhiZfKJfr16VL
            BAnnCDbNVmfxXhDfm3x1krlpr988L77OU/IctHaXkm/soQMQfwQJ14f9NmIr8eXS
            XgGwx7LytC94wjA2JQWlSUgeW8hPW8f8LFK4nz8SrNGGd/Zdn8O4wxe/6TV+mlv6
            62wiXxDYyBwEu9gX2/CdMyWfFcf0NkUxrIltX24f194ARhiHQ9InCgqPLFgJI3E=
            =D+hb
            -----END PGP MESSAGE-----
          fp: 57CDE9D844F97A3A7161458CD4514EB8DEB5A564
    unencrypted_suffix: _unencrypted
    version: 3.7.3
---
apiVersion: ENC[AES256_GCM,data:Piw=,iv:vJi7ditWesRtw8Q+5HCcN7syPQ5S1xRoWdut27PFees=,tag:85LBURLQSt5tArP1+QNs4w==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:7EL9s9+bg3tI4nWUZoGXHyJxJY32dfraMgwC+FEU2JwoD8Ro6zNGuKg6vkyQcWP/MxWLRGdbHSv9dVCNeiqqhdUazrZf5Wp71lgeZDxKpTUsck9o2WHOUw5+nTR5TZ6lCaeeb8MqIYPvrtTQL0dIUweIKfjO/cnLUKHjWaa6WFIccMOln9HpF5pLCR0=,iv:cDN4jkx0UP/cJqvL2e98O39pdR+y0iVpoc3Af7/R01w=,tag:4njoRDvrUvbZiyLSG9S8uA==,type:str]
kind: ENC[AES256_GCM,data:YmZ6uId+,iv:e65GNp5wBBCMGxY5C5Y1Bsy9ObNOXqO0dPgwH0RlirI=,tag:5jdZRXbSTbMOK8L1oMGP5w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2I8kT0qDr2+CjYhRDVX2qOM=,iv:xR4Qx9DB57BYdvav7Pcm0N3VMBQ8kEPaEWHH/W/4kK8=,tag:zi7uqZI3rSWSDXBqhqY7WA==,type:str]
    namespace: ENC[AES256_GCM,data:sOUFPqWzqO7sM1V9yWtgdgZqvw==,iv:bI5ZP6qJ05rt+ZL5XyA1UDp/GbVXcqOJq7ULqvjCU3I=,tag:PjodDrFabW3ZslKJlhZakQ==,type:str]
type: ENC[AES256_GCM,data:KNWXpzKNwDX5drqVjxvUvf/CzFWGvq2CGHwis+bj,iv:xFmisJluo1pTn02XuewvpfpuQxHbI/y+eR6NMnLQXu8=,tag:BAzHn7+ltjmZpW6RBqN0og==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-10-19T15:48:05Z"
    mac: ENC[AES256_GCM,data:Sx1qj5tYrWH0/PST1962SUAtyPK6hjJO4uSSNUBksdDI9Hm/k/x16+hrg7MHebEdDcnUHlopAbtvBmBgJn06VkkDBKWTBEAT4AM4inyv/S8nsg8RYIw72tkzelT6O//CkSlw3mTI1X3WbwX1Cv385D1AV0AsQS1VTsIKaSoj9CM=,iv:wpJiJ/LQtDdBUoEsnzo4oArTV74IvDsMdaoND52UZLc=,tag:y2TqpII+1DEe3WWg9QSu4g==,type:str]
    pgp:
        - created_at: "2022-10-18T21:00:30Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0FQ4OXZhO54AQ//R51F/hR6U2zxTvyRziasecAjx0yXKD4ntR8xlWonjY1V
            YP4xlnI1gUwZTnt4fyfYkz1Qn8XiKt6P+5ee7nFwgHQ/Ay85Xkmjjx8hNqQtPZVJ
            jtg/BBqbHcg0BbybYLnWKmNFt1cSLCRm4CUDLP02LtIP/h8GkI6zz/Mtri4SEVq1
            AAeufmvOjBfRGLcKiuUGA7gDCMOV4K7TL8wX1i0BR9Fbr6eXbS4DsHZ8l+Y8UGXh
            CYd4JUwdF9WQq2mK7XG7+evJdBqXJFJTl8F2VHL6i8vJLp4diU8TA9M91HJ4qrMW
            ky/CTOXrGTFWCutfch5xEtHE6KNuYBGL5l1nWOFt0ceDubSTROWY6Nfb+F9NWMZ+
            CyB+3QCV2I/bee71/aTxaYdMX7fyHuscSbKrCSA0k07UW850sMW3vie47NrohDwz
            XLUknotYtQ5EaC5dxtyOLCRnkFEpoQM97s/41C959R/vJOed/SId6lbCSer4HEGz
            4C90YG9b8V69zu92m+xo+jP7TxfqgkLcWnlQ2gCpzozgUCUX2waJD0dyIxnbIJez
            bxhs2LnXttyZ9oKoH8wFFS8teMpJ7L4YcqPewZYa92w9AvYQpImhhiZfKJfr16VL
            BAnnCDbNVmfxXhDfm3x1krlpr988L77OU/IctHaXkm/soQMQfwQJ14f9NmIr8eXS
            XgGwx7LytC94wjA2JQWlSUgeW8hPW8f8LFK4nz8SrNGGd/Zdn8O4wxe/6TV+mlv6
            62wiXxDYyBwEu9gX2/CdMyWfFcf0NkUxrIltX24f194ARhiHQ9InCgqPLFgJI3E=
            =D+hb
            -----END PGP MESSAGE-----
          fp: 57CDE9D844F97A3A7161458CD4514EB8DEB5A564
    unencrypted_suffix: _unencrypted
    version: 3.7.3
---
apiVersion: ENC[AES256_GCM,data:xw+jVAfsd8XzleOEhTGTSUwTHXDpQE6sjyrf0AE=,iv:EH6OyNAIF2aOJ2yMOPsa1wxj/mJKVZm+z1mG9778eA8=,tag:JbrIxIWRcIIRsxcO6vTyPA==,type:str]
kind: ENC[AES256_GCM,data:sl2SfSse69aC7zYH8DL/Ul8=,iv:s2UDYqj4ZREleb4fy2lKylXuY+x3jrosrNvFuQOseYU=,tag:6C9am/Dlxo4vozkRaR4cUA==,type:str]
metadata:
    annotations:
        tanzu.vmware.com/owner: ENC[AES256_GCM,data:uNcT,iv:ljKt5cXueJD2g9YY3U7GkyWvpY89Yiqwh41Jqs6ygGA=,tag:bmQTiF5IXpEn2flVs31e3A==,type:str]
    name: ENC[AES256_GCM,data:lvicE4VW1II6h/yl3rgIKl8fqeu5qQ==,iv:PZI66URCNqsDqm3Gm6akNPQMwHbIWX/HZVKgxTIHYEE=,tag:yLSzY4NckML1PqHOjL69MA==,type:str]
    namespace: ENC[AES256_GCM,data:sOUFPqWzqO7sM1V9yWtgdgZqvw==,iv:bI5ZP6qJ05rt+ZL5XyA1UDp/GbVXcqOJq7ULqvjCU3I=,tag:PjodDrFabW3ZslKJlhZakQ==,type:str]
spec:
    fetch:
        imgpkgBundle:
            image: ENC[AES256_GCM,data:4B30UvkipjHCwoLwSWDN94BLQbRAUr+MZEKN8bMp8oFp9scvw9jzLkWNLKyuSTEwo71plZxwptuhgLVSpylKTUFJlpXjZ3GSS6jUFA==,iv:jJg9JvVboetk2ikYbNy5KezwKAnJE+aJLcMEbtnjrW4=,tag:ohgj2EQtPTZ/KRxkYcU71A==,type:str]
            secretRef:
                name: ENC[AES256_GCM,data:rFartRDm5n5l+0xPEVKNPIHb3Mg=,iv:nHlyuDPvtY5eZchY0kwh/xLFXLnaN6tSalOhG/Oyvsg=,tag:CDAmASsy+dRg6S7918dsQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-10-19T15:48:05Z"
    mac: ENC[AES256_GCM,data:Sx1qj5tYrWH0/PST1962SUAtyPK6hjJO4uSSNUBksdDI9Hm/k/x16+hrg7MHebEdDcnUHlopAbtvBmBgJn06VkkDBKWTBEAT4AM4inyv/S8nsg8RYIw72tkzelT6O//CkSlw3mTI1X3WbwX1Cv385D1AV0AsQS1VTsIKaSoj9CM=,iv:wpJiJ/LQtDdBUoEsnzo4oArTV74IvDsMdaoND52UZLc=,tag:y2TqpII+1DEe3WWg9QSu4g==,type:str]
    pgp:
        - created_at: "2022-10-18T21:00:30Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0FQ4OXZhO54AQ//R51F/hR6U2zxTvyRziasecAjx0yXKD4ntR8xlWonjY1V
            YP4xlnI1gUwZTnt4fyfYkz1Qn8XiKt6P+5ee7nFwgHQ/Ay85Xkmjjx8hNqQtPZVJ
            jtg/BBqbHcg0BbybYLnWKmNFt1cSLCRm4CUDLP02LtIP/h8GkI6zz/Mtri4SEVq1
            AAeufmvOjBfRGLcKiuUGA7gDCMOV4K7TL8wX1i0BR9Fbr6eXbS4DsHZ8l+Y8UGXh
            CYd4JUwdF9WQq2mK7XG7+evJdBqXJFJTl8F2VHL6i8vJLp4diU8TA9M91HJ4qrMW
            ky/CTOXrGTFWCutfch5xEtHE6KNuYBGL5l1nWOFt0ceDubSTROWY6Nfb+F9NWMZ+
            CyB+3QCV2I/bee71/aTxaYdMX7fyHuscSbKrCSA0k07UW850sMW3vie47NrohDwz
            XLUknotYtQ5EaC5dxtyOLCRnkFEpoQM97s/41C959R/vJOed/SId6lbCSer4HEGz
            4C90YG9b8V69zu92m+xo+jP7TxfqgkLcWnlQ2gCpzozgUCUX2waJD0dyIxnbIJez
            bxhs2LnXttyZ9oKoH8wFFS8teMpJ7L4YcqPewZYa92w9AvYQpImhhiZfKJfr16VL
            BAnnCDbNVmfxXhDfm3x1krlpr988L77OU/IctHaXkm/soQMQfwQJ14f9NmIr8eXS
            XgGwx7LytC94wjA2JQWlSUgeW8hPW8f8LFK4nz8SrNGGd/Zdn8O4wxe/6TV+mlv6
            62wiXxDYyBwEu9gX2/CdMyWfFcf0NkUxrIltX24f194ARhiHQ9InCgqPLFgJI3E=
            =D+hb
            -----END PGP MESSAGE-----
          fp: 57CDE9D844F97A3A7161458CD4514EB8DEB5A564
    unencrypted_suffix: _unencrypted
    version: 3.7.3
---
apiVersion: ENC[AES256_GCM,data:xw+jVAfsd8XzleOEhTGTSUwTHXDpQE6sjyrf0AE=,iv:EH6OyNAIF2aOJ2yMOPsa1wxj/mJKVZm+z1mG9778eA8=,tag:JbrIxIWRcIIRsxcO6vTyPA==,type:str]
kind: ENC[AES256_GCM,data:1AbSgiOpGWmowwF7O+E=,iv:0yecBLu3HDiwu7Be5JE5bwcRb79JAQkmE0l6uS8PMVc=,tag:hEnnE7oAi6nQkZvjIp09YA==,type:str]
metadata:
    annotations:
        tkg.tanzu.vmware.com/tanzu-package-ClusterRole: ENC[AES256_GCM,data:ZIfljrnzyE9kkty36oyNXOViNMsYVXHRUw==,iv:el758iQd5b3QnB+aRQnx+T0VWjOCj7aFEkrcYmXBakk=,tag:P1r4JRrvxYu6uAVyOrLN0A==,type:str]
        tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: ENC[AES256_GCM,data:uz4oFiQz03KFaVnJJqhdBVpRFfV2NSw1VhKSdIl+8M4=,iv:Acf+CL9nT/SNkMCIPijSkDyQXOATxMV0CBmM5wISMws=,tag:kVZY0cclixx4L+8NbONeIg==,type:str]
        tkg.tanzu.vmware.com/tanzu-package-Secret: ENC[AES256_GCM,data:VcA3G70xeFfY0SYKRR4ypSpbhw==,iv:kB1uxS09irGef+Z9YQflikaVdSjJjA3jQfOAvtC/qS0=,tag:Hc1q9+VtW7yIk+x3qUsBvQ==,type:str]
        tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: ENC[AES256_GCM,data:JqGTtSYLWyxtrOyXZaPc,iv:wD1h1hgm9fpFNgylNDvRSWdXS0+1D148z4bwmBBrfiw=,tag:Kjn1Khl3YBsDZdWdh4XAug==,type:str]
    name: ENC[AES256_GCM,data:8jhy,iv:GlNg4/L8YamDMClt75XtFQzUrRaaIlmuT3Rfee0cWdU=,tag:vlIg3lmeixhoGzGTGcNd1w==,type:str]
    namespace: ENC[AES256_GCM,data:sOUFPqWzqO7sM1V9yWtgdgZqvw==,iv:bI5ZP6qJ05rt+ZL5XyA1UDp/GbVXcqOJq7ULqvjCU3I=,tag:PjodDrFabW3ZslKJlhZakQ==,type:str]
spec:
    serviceAccountName: ENC[AES256_GCM,data:VftfmBHneMzE1N0Uz+tA,iv:hVmQjg5nwBTByw+6ykTiBno8bse0IRgfFNxffjSLo5E=,tag:IHIGZ+FB4R45ikqxBHiUoQ==,type:str]
    packageRef:
        refName: ENC[AES256_GCM,data:aSSn+aLLJefWcNw1RhuktMR8VUDsMO4Yd54xU8xSbXZaEgw+3rS8DXeaa4o=,iv:GLNNWR2fi6N+EHGs+/vQkpa+2HZgJb2gwtwjjNnvgwA=,tag:wU3BCRGibxBTmmYrH/ImIQ==,type:str]
        versionSelection:
            constraints: ENC[AES256_GCM,data:rURM0/8=,iv:jHMhXNIsTdxIq0YNitqmEDG816D00B3Mes2tLcrO6sc=,tag:apuanMXMMErr4hf5U+pQOg==,type:str]
    values:
        - secretRef:
            name: ENC[AES256_GCM,data:21zjtOvJYjhch1ay+JCNOqgMew==,iv:fQSrGdLy4d+/n9agGCeHUW9dxJBIps6UNo62grQld7M=,tag:vmdoFiFiBv7W8BbbuHDiYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-10-19T15:48:05Z"
    mac: ENC[AES256_GCM,data:Sx1qj5tYrWH0/PST1962SUAtyPK6hjJO4uSSNUBksdDI9Hm/k/x16+hrg7MHebEdDcnUHlopAbtvBmBgJn06VkkDBKWTBEAT4AM4inyv/S8nsg8RYIw72tkzelT6O//CkSlw3mTI1X3WbwX1Cv385D1AV0AsQS1VTsIKaSoj9CM=,iv:wpJiJ/LQtDdBUoEsnzo4oArTV74IvDsMdaoND52UZLc=,tag:y2TqpII+1DEe3WWg9QSu4g==,type:str]
    pgp:
        - created_at: "2022-10-18T21:00:30Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0FQ4OXZhO54AQ//R51F/hR6U2zxTvyRziasecAjx0yXKD4ntR8xlWonjY1V
            YP4xlnI1gUwZTnt4fyfYkz1Qn8XiKt6P+5ee7nFwgHQ/Ay85Xkmjjx8hNqQtPZVJ
            jtg/BBqbHcg0BbybYLnWKmNFt1cSLCRm4CUDLP02LtIP/h8GkI6zz/Mtri4SEVq1
            AAeufmvOjBfRGLcKiuUGA7gDCMOV4K7TL8wX1i0BR9Fbr6eXbS4DsHZ8l+Y8UGXh
            CYd4JUwdF9WQq2mK7XG7+evJdBqXJFJTl8F2VHL6i8vJLp4diU8TA9M91HJ4qrMW
            ky/CTOXrGTFWCutfch5xEtHE6KNuYBGL5l1nWOFt0ceDubSTROWY6Nfb+F9NWMZ+
            CyB+3QCV2I/bee71/aTxaYdMX7fyHuscSbKrCSA0k07UW850sMW3vie47NrohDwz
            XLUknotYtQ5EaC5dxtyOLCRnkFEpoQM97s/41C959R/vJOed/SId6lbCSer4HEGz
            4C90YG9b8V69zu92m+xo+jP7TxfqgkLcWnlQ2gCpzozgUCUX2waJD0dyIxnbIJez
            bxhs2LnXttyZ9oKoH8wFFS8teMpJ7L4YcqPewZYa92w9AvYQpImhhiZfKJfr16VL
            BAnnCDbNVmfxXhDfm3x1krlpr988L77OU/IctHaXkm/soQMQfwQJ14f9NmIr8eXS
            XgGwx7LytC94wjA2JQWlSUgeW8hPW8f8LFK4nz8SrNGGd/Zdn8O4wxe/6TV+mlv6
            62wiXxDYyBwEu9gX2/CdMyWfFcf0NkUxrIltX24f194ARhiHQ9InCgqPLFgJI3E=
            =D+hb
            -----END PGP MESSAGE-----
          fp: 57CDE9D844F97A3A7161458CD4514EB8DEB5A564
    unencrypted_suffix: _unencrypted
    version: 3.7.3
