#ENC[AES256_GCM,data:PSEmfN/sM4Q12e+g7EKUyy0vvoF7kzMiP3OSdJcklN4JHgvEdhx7WHoiE4RkHDMdIYNMt6lnt+Qu/KeY,iv:xsTHYvV7/vd2MXka9j9V7LSikkNzQsZYzeP3yFmMC+M=,tag:F4Ql5bB7n+yqWxPrW+ZZmw==,type:comment]
#ENC[AES256_GCM,data:mErmIUYRIvc4cb6vZFrkCdh7/6iNmvkHCyifzCNcBLUbBpKZmVpFrD2BqAC8xSFq4pHiiUfU0aZAeUSznQ==,iv:KhnoFw2aPhJnEubtGWfaAFp3L643Dpl+mf7aw5NtEBA=,tag:UzqHOi6JFJfEqi2MoPLHZw==,type:comment]
ceip_policy_disclosed: ENC[AES256_GCM,data:lzsFYg==,iv:0Pw5iXKYupTXiQydIJIOWg5THKmKm+KbpYx4w7wUt9s=,tag:WV7kDk8xiprfhWCFXXn5KQ==,type:bool]
api_ingress:
    fqdn: ENC[AES256_GCM,data:oymEvIgs70PDXXPUZ/Op82z6nwTyrCsh,iv:sfiI/ANB1sovPsxd+w+D/6R9e/u9OYneRmWqfTT4Wd0=,tag:YgIZWITDyV2f1bWnUeC0/g==,type:str]
    tls:
        secret_name: ENC[AES256_GCM,data:3RCd4w4wqF9LbldsQwoJIBO4r6iqBJOMB/1Y0A==,iv:6sVwpTYrqKuEt7Yve25y+sAb6LNBceWgCixQVEs/9yw=,tag:4wtb0qx+ieiInCTZEaontw==,type:str]
        namespace: ENC[AES256_GCM,data:tHFX9YNIx1lt9UqX4lBXirARtg==,iv:P9FSbNf3BczzC3lU08XP38fpCodE3rdQuhrGxJXhzI0=,tag:PbU/8cnqTTl0yIyyymBvGg==,type:str]
app_ingress:
    default_domain: ENC[AES256_GCM,data:+tgpqPwAUgoG6uTeP1rYBBE=,iv:5oD+qEKr2niOz0+vkgVG8eTCITdFyVmY4m+amYHFcZ4=,tag:0N92o+5777vATVUaHLm9Nw==,type:str]
    tls:
        secret_name: ENC[AES256_GCM,data:Qf3L0l2sgTIT3SNRCGcQyp+qDybc,iv:9eH5U+6ZJR4e3GTqkiDFcvOevS2iSWRu5aZ9uqXWCLM=,tag:3eRXlgruu8KvYPs9BoXR6A==,type:str]
        namespace: ENC[AES256_GCM,data:MxWrB8E39PE5kyffwJAs0QfM9Q==,iv:DcwyxMIZKBSR0SW++tpEsRs0rgoNcCFZFfhH8OFmR3w=,tag:y5kOCd9oN9LvnJ1gXoWxLA==,type:str]
app_registry:
    credentials:
        username: ENC[AES256_GCM,data:q25bAg==,iv:bXUCX0jS4ocjYQ8YzLMgoOqqByXZtUf9/TlLN2J7O0w=,tag:bY+dTM/qQ+WsZKhb/vgjUg==,type:str]
        password: ENC[AES256_GCM,data:JKv12Q==,iv:3nU/oCFfLSRaslAIAFHjKmFkkfMmky52L+8hbwA7QoM=,tag:+srbyTM5Wam94Ti4nbe+Xg==,type:str]
    hostname: ENC[AES256_GCM,data:ujW4JQ==,iv:uB4I74xlJbK82ZfhlmM2xsJGGtthzMhSoDtzD3G9S2U=,tag:zKcfzFJE4fC8S02eEtc0Kw==,type:str]
    path:
        droplets: ENC[AES256_GCM,data:evWDlYMxCpYqLygsb0913UaL1dD6J/IQ+qQ2Wg==,iv:SSDVcemeqkN/rXov0FqIaGvPnfZAhQ+DZhiA0ohvLyI=,tag:NJ0M/hp5WW8FJfci8hLFVQ==,type:str]
        packages: ENC[AES256_GCM,data:K7znLY/8WCSnkDzNFUZpz8HpUG3a8t8Yk+TQSF4=,iv:5e3tiFikE3CqXqqcXEof4mt+GYuumptmVGCy96Jh67E=,tag:4SBILPkuvzd/M++CuJGm7A==,type:str]
        #ENC[AES256_GCM,data:SlTB5aqXTmF4,iv:05WwqEm/7Cn27zAYvIiHfB+4go4BIO210V27EjzxzPM=,tag:ZWQNakKXjvuVnm+yWWVP5w==,type:comment]
        #ENC[AES256_GCM,data:eiM/IvDR7TcCTQ==,iv:5Giljsml+XH/SU3URZSuk9+/8S8+96hMNWcBwLC8zN0=,tag:enqihNCp+JZUBaswaN0QJg==,type:comment]
        #ENC[AES256_GCM,data:eKzHa5sXht2ysx2c0yoQ4JMPVfzNrIbe1LyNtYq81d4sB5q9SQ==,iv:teTw5x6KkF8PXqu+S8cMNr165sl8pJR3pkgGOQ5S/q4=,tag:znDws25QFs+QMoQGMWldmQ==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-01T18:35:36Z"
    mac: ENC[AES256_GCM,data:9nCRRgnx9w3tNMZqZcE2+2y9tIYcy3Dn9wcmXR6dt7rjVdQ+ZTAkZtbix7hRQ5JsWe0sqiLZ5wytTt9J4yFTn0C8TytJt13NU8IBqraXrJ8EdjrIy6YLAgZC7ZwQYethWYZHYzWgJmq2ewq+rrXpYf3fkJnpho3LdUw9VM2Jiq0=,iv:7L1b9vI3fDsZoGavhQMYPBGZwaf2+u6vdErHXY8rGv4=,tag:gbdMja0w8+f6+37Ak/0ydA==,type:str]
    pgp:
        - created_at: "2022-11-01T18:35:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA5xDFa4re5I2AQwAlVZ/kH/Jdcf/s7Cc+F6HqL3Mpn91k+nC4OxN1EaRvktO
            EcyxEBxS2VUQb+Bll4FUl1dVsQqeqLGSryg7Me/tHyvDdpOT6tKxiZW07VpNy3fW
            9ZK1YROvHYIaI8jRdstzHHB91Ez1/9lajSz6N0wa2OC30MT7zlCNfHbQWUSi3gU/
            ZziNncy8RDMTfSE4f7zkEG7jgk4zcETqOLCOaIVj3Yt3cqD3KX4KYsxV4Vki4vsr
            jLtB05bofo0DcjVNj/RpBbeH9rNYu0LFf500DaBLEEqgiEkW/QZsnX9qn6i04B1j
            /zxDS1bctSpq478zvl4V4j7LO4dV8j9kaAqVYYQ1yFQMIHnKuwu9jUP/ZHNKmfu0
            lke7KlO9puwGdPa/w8nqTStbtUTrweogLv0uMiovFvXIBUsqs0JbInVGspFgx4IS
            iKdGf/FioZgf9SYpG1ib8fh/JLCdw1WAiJXJaHHO+Uq/lbX3WEmdIRmX6RxFouIz
            /K6ulF5fr60Xzp6qi7XP0l4BYlDDHOXmK0OKidNExvvlD3RTu7oCeGFxW1qN/i8s
            WbI/bsmcqocsdcdbNHvgg9mQCWT7EfuYnTckQ8Gr8lH45vKFZ3Sj7fM0wRh1PXoY
            qqlJkONGAoefd8ybtstN
            =bBA4
            -----END PGP MESSAGE-----
          fp: 80757AC15B96B550CD3474D7AB0F930BD7A41E06
    unencrypted_suffix: _unencrypted
    version: 3.7.3
