#ENC[AES256_GCM,data:5ly/ncG2OlyRA+3BAlJ2OchkgF/glmJ+kbh9tHy+o39diJDVlzmdcJNtSuXTYEKl0MYKm0kcQTBl5CeI,iv:nOPPoqJdQ4+3LhlwY+xy2s9hEM7lDF4vV7t+xDZWIn0=,tag:+xMo/2pypJn1HYjVWSXtaA==,type:comment]
#ENC[AES256_GCM,data:mhzGj7oIVeQkIps3YhBIgxHgdqHU77I2HbENc7g1+99z/+ZkqA7rByTwChJVyhFsdxL2oTd3H4iMplx1+Q==,iv:HomIKcJDijVZEOBcfX1iLvIeY2nfcmYfhl5tIsuCZcM=,tag:8fqnjOiuRz7bIiqzwijCXA==,type:comment]
ceip_policy_disclosed: ENC[AES256_GCM,data:3zNPKA==,iv:NrTUP5x+wQUQWJFPXavZusZv+lxOLruOPaHbf6PbGLw=,tag:j+skBixzB+XK55zs4l6EcQ==,type:bool]
api_ingress:
    fqdn: ENC[AES256_GCM,data:IKHu4g2FrKHaUX6yLJ6ZMfZj+sVnC23M,iv:H5KYvbKbJWCNaj0qlOpl39FtNE81nVAqMzQWpum50d8=,tag:kSXkOZP0xfU5zGWaVxHmzw==,type:str]
    tls:
        secret_name: ENC[AES256_GCM,data:x6F623+qfg1GuvoTZvF632WKwjW+PTjebG3StQ==,iv:5dJJXUvb3Afi+GiXkt5Sdi1rj2GsW5y0z7yVy4CU7AY=,tag:CaJ1uhTq9ShCONpc8LtP1A==,type:str]
        namespace: ENC[AES256_GCM,data:jRZiyWtcHAStDVMjNs7c7pxkXQ==,iv:E285Vbpef2fcAw4O+XaPkyWQeKEjepsBv4Y4oFx346w=,tag:tH9gaVKxEWMAw9W8DZcjGQ==,type:str]
app_ingress:
    default_domain: ENC[AES256_GCM,data:YuAzIPLNGAUSF8VG7k7yrc8=,iv:dQaN9D+sLH2/3LzI7mgaI2FIYy2Ciao+oZVtbNWCNmo=,tag:5RfYWFy+rZOYYites+uh+A==,type:str]
    tls:
        secret_name: ENC[AES256_GCM,data:yEUBazRbVG1gQgVPP5Cv7FPzkEQn,iv:T8bMj64/urlKNEwfcIR0UJo/RGpPYysKNfpjnomy06c=,tag:3a/ZhmvCdoosevz6yd8qbg==,type:str]
        namespace: ENC[AES256_GCM,data:MH5MdbrODqo38PZ+JcODgFFXiQ==,iv:NW0YMRuVdyS/11eraCQvyet0iFtp6RfvUKrkPo2kNtM=,tag:Jj8Y2rMrVApf7DpGRVt72w==,type:str]
app_registry:
    credentials:
        username: ENC[AES256_GCM,data:TauZJAI=,iv:dZKsKHi+7FP7vGskmdpUiUR7Qd2sKNqaCZqoSZgEjMY=,tag:xjiweP8u/aj6xN0y3WE3pg==,type:str]
        password: ENC[AES256_GCM,data:0nP0/7lQwNc=,iv:CNcUClypjaYopqBHwBOONNUGLmHAB7oes0xolrHXrZM=,tag:oO8HlcMDQx2rZkALWPlyuw==,type:str]
    hostname: ENC[AES256_GCM,data:sdZ2hu6uusf+6Bazb92IVOzTaQ==,iv:XZDk4Zt15JxaI8ZrNnIe0rnsjkBsTSlUQwPybN4yhms=,tag:dj54P7iFrWLCRWgN97fPAQ==,type:str]
    path:
        droplets: ENC[AES256_GCM,data:08f0xR5ehSxhWChE1zv/dL6r9k7q3FdyW672Hw==,iv:rAawcfbRzAsTrKYdxtV9emZa2XGlKTr3dkiVvBhhA/o=,tag:WCkWK+ytbS1db8IuanQ2sw==,type:str]
        packages: ENC[AES256_GCM,data:dO3wZ+hPhzlnxpKhuMEAF4dBUcaWT6CkCny8BVM=,iv:vf9XtNeFJNMWrLRe6S7HqmPjcWYSg6UNtSVonWHH3F4=,tag:+CQcHDd2ylHUcptL+ugaYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-10-18T20:18:13Z"
    mac: ENC[AES256_GCM,data:jA091VEWMnvoOaRUyTncdjRdWbJVSJnJ/OJ/iOMMIpX8kvPY+Od2zqmLiPCmNQuLG/D8eQkPchFKJcoC79KeqcrTsr6RR+3AfT3/7sgfUltdJubcqgt+5M+jYubAdVw91uRSyZhootyo9RYrFHO5PT84xL/hi1WT6iCgIfzUiPA=,iv:4NEaCL/lQvn5MFP/4yBXtXg2X9LCcS9tD7/tbYEKW6c=,tag:wdKr9ucUO6wc6OrmAPwwbw==,type:str]
    pgp:
        - created_at: "2022-10-18T20:18:12Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0FQ4OXZhO54AQ//X0g7Y9SfKLG5HYARZr5KQ2BsD5tW+fsIbSh4o8FFvBFQ
            t6gHiacGgs7eRKBKuzbwTMNiwKVkwpXlQNx7BBJkL9OmJagqC5xXHYslnag5A+c6
            NLGjT+VKNx81gOoGM6e8GdcY5989vpozHI9AnK1wNpqikUgwc6Qm+ZRpUtXe7b37
            LzrW20uVIk7M62UHnPC0bBLRS9zeu3TqfwqpYp+eJ3cU98YlrtZN2xUohWkfaFoc
            SZf63i+T9vKLf/n36GhjVhaQK31sNHLPs3rAGU7pLeLKytqi8w2FsN3O/6b+WZlM
            jxGA2qnOqjVE4zV6haWmla/714GO2knwqKhg7DMby3sdP/JD4Xm+FNXn1gtkYjHP
            cFhPLrz+AcUr/RD4AX3y+Gd/IIDheVqR9RGEJ7J1KkZjkM7IjFYuE0mMGathfQlu
            z8G1eHzpk2u5ULVhmzPA9+Vlenc8mJuU7CuWkCrtsY5Fb2poAvOFd1zlVUOByQ8d
            MC9kDEV1tEMNTWgIuL74uLxT9RAOg7O/DJ97M3oVVwf5A34Wlr1I2qcqC8nQZlBG
            0K5hz7lkhsyei19edeUxIwK/HumBcu2snh9xOrZZ/P4s1z4JxrpyfnzuY/RZpkI1
            xN/K27d8EGqsbB2uilq+YL9YNTDuDUPdnkwfX+1Le1IfvApslGA0s4HwmvN4tpfS
            XAHWjpDmj1jl8xZM4+OmnXuoAwnQeUAwuUDZPSQrk2pivscQ64lS72rKEkULHKo/
            hvyfRZP8C4WLbN7fS+1Y4pya5Qpd+nMRlZWuHiM/bOpkF+ZU7A9qxvUTP5HE
            =nw6O
            -----END PGP MESSAGE-----
          fp: 57CDE9D844F97A3A7161458CD4514EB8DEB5A564
    unencrypted_suffix: _unencrypted
    version: 3.7.3
