apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: tas-packages-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: tas-packages-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-Secret: tas-packages-values
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: tas-packages-sa
  name: tas
  namespace: tas-adapter-install
spec:
  serviceAccountName: tas-packages-sa
  packageRef:
    refName: application-service-adapter.tanzu.vmware.com
    versionSelection:
      constraints: 0.9.0
  values:
  - secretRef:
      name: tas-packages-values
