apiVersion: ENC[AES256_GCM,data:37Y=,iv:yKDm/kTy3Go6zJQqe4hCpWpxVnTMIrbhZXBa0GWGVpY=,tag:4JrYayR9k+JkqzDB/7EoLQ==,type:str]
kind: ENC[AES256_GCM,data:EDQH16jhwBJD,iv:7stsrxnU8o8ejh4bxzGeM2pEDcegFFO78CDyjyysnb0=,tag:pb/UTcc1XN5IrtYXMYryxA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:JDhKNo4TORdl8OqqwmLbLayVuw==,iv:WBQmOR3qyX+phx1/ru9unF6fN/rjU94qYMjTrJoRw9Y=,tag:UwaSrhhx9EjHqub1N4bI0g==,type:str]
    labels:
        name: ENC[AES256_GCM,data:o9xrNkvxZQ42nL/UhbBNhC6LFg==,iv:hY6JZu9s5L0H6tKQWPx1dU91zDOwCxbxyHxwYUckkSo=,tag:dxEg3vvW4NaAhhk6+Be93w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-10-19T17:34:38Z"
    mac: ENC[AES256_GCM,data:/fvRB5H4EcSOHnPA7+/FxDre2pmev1AfeNLlDeTBYF1vGtQ/4eZY6+3cd+tEZ3amzY6UGb75Sm0vccOV6OGeQsr5UJ+KcAiOLVpUoju5B/8iuQn+NDBY8ISqljEZiHlSTLmKd09pLB0YwwFUai+3sodyqYMJ1A5p0ku4gsfjv04=,iv:VDJVuEUOHWymgQ8FUqRCId0y14P0gHpAGIPQIJOAs4o=,tag:TrSP5oVI93FneJZve3cIFw==,type:str]
    pgp:
        - created_at: "2022-10-19T17:34:36Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0FQ4OXZhO54AQ/8Crolddaa+z6yC1Yq5lN0hzuK/nYCC2bSzirqQ6MnPZKy
            fqyv3zq0VbG5goLCBPWKgkaYX2rt4jOnuhZrXcVOIH26nqJPYDiuhxTeEPkxzWne
            CyTn3l0mGBJy5Yq4j1i0ECFvOdVn6sr+zgXq8Tp8UnQDTmNCwcKBrLI/w1EPd/MI
            ZCUM8jFqfGK03CyIRj2Dir3i3Yd9/eIEqfiG5GwceM7RYCbxeV/G7Yby3qo9fKGw
            mIO5OyJ56tOkp+ImLdeGVWAHhrcsanMGFuVbdioXJpXtmpKUWqvwiX6Geec6jHe/
            PYu1DzqRUyzPUCkwgse/IMV9KUQCm51nAC8wl4jqOphO7/kYZaALVXCJzh0Q2RvH
            FBeoyY5CsiPKBkyuLGk0bv40r6cQPfZ2hPTWRfANhZ94QLSkhPVMxlyEl7BSY+n8
            Sq9UoOnQNsq7PB7+NtdUGmv2rWNZ/o42mFB1yatvI5kNWanCQPXxWTpw1HfJPb2+
            qH9OwHyxMEGZHX/GQEfjRl69z4IRvIxiBp+E7D/7ScT9SzlzCBskL0VvPRNKFMkG
            3Zw3ZIZkhoA/uIMNWKKP4Wb0ebQio+HhcvG05BM+8kjIW2vWkBp7fkduYaGwE5vM
            7z+FmynxpAv7tNftMLxK80EiRrYmq/eBWdxcxhAuhpW9TDza76+0H9sOH5c5z3XS
            XgEL4phOcF/tHObFY+urqyY2lB1t9AufFu8i9ZDBghloFY/sY8RBLLcUXTckbtBz
            gTdeRLomJ4T2pA0OoDZlrSX4FhCHLGdX0Fbhy3AVTxiDjfGCbYWW0GWlHzNLE2U=
            =ahOm
            -----END PGP MESSAGE-----
          fp: 57CDE9D844F97A3A7161458CD4514EB8DEB5A564
    unencrypted_suffix: _unencrypted
    version: 3.7.3
---
apiVersion: ENC[AES256_GCM,data:w5I=,iv:mo7CDCxqYpDT2/gGaKBVp4ENyu7rmWrqx9x+b+B52xw=,tag:b4rcwhrz/E64ROiY1k8m4Q==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:riQ4gZbQE0a8+flu/Pv+DPvA/IDX5dHH2aZ7wf7ABeTn+kHTprCjJ7Mtgb0tWR3T8D8V66oTRtooWNmvXLycO3o2XyX2q54jpKeeacPpf3OQ0AQ2ZPSdAHTUUApKiUVOowtH233iPRC5f35w07wT9m+P8t0y59AvqGWbzIziMoOG425vlrOiWvvl7Kg=,iv:1zBZn7zexpLIE4FhWKzui6ACQWZpbunyJe3Gs+qrVmw=,tag:5JFt4Qw6dAO1AeuRpOeKFw==,type:str]
kind: ENC[AES256_GCM,data:hsV+lV68,iv:8hCfV7Puftz+x2CLvSMEm38uqqbce8NrFZGnaHF4tig=,tag:COBo9jaCnhT8vMqFdbqRBQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:gwljKaOXbxgiJd4dhap5aTQ=,iv:f78QM/wnv8WSK4oh4lwUlsNpN5xfzlPeAshAYV174lA=,tag:/QUrN44ps+71d63//Cijig==,type:str]
    namespace: ENC[AES256_GCM,data:1ea0OC04Cr4dJnljcm//7xv6vQ==,iv:ywQyv/AfMUWlzDb5VAFx1BYill4n7SFLUvCYtgOd0Cc=,tag:FyRR3iuSXXAnKNF8+uLN1g==,type:str]
type: ENC[AES256_GCM,data:yksGw1vRVjQd7k2682IHjQeh5Xs6hATn/T5RL8HV,iv:jamgbLYCax8glbicQi7gsratuhMIDxpeQYvGT1EyeSs=,tag:6OkwYxHLFJaM6ZPi7vkD6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-10-19T17:34:38Z"
    mac: ENC[AES256_GCM,data:/fvRB5H4EcSOHnPA7+/FxDre2pmev1AfeNLlDeTBYF1vGtQ/4eZY6+3cd+tEZ3amzY6UGb75Sm0vccOV6OGeQsr5UJ+KcAiOLVpUoju5B/8iuQn+NDBY8ISqljEZiHlSTLmKd09pLB0YwwFUai+3sodyqYMJ1A5p0ku4gsfjv04=,iv:VDJVuEUOHWymgQ8FUqRCId0y14P0gHpAGIPQIJOAs4o=,tag:TrSP5oVI93FneJZve3cIFw==,type:str]
    pgp:
        - created_at: "2022-10-19T17:34:36Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0FQ4OXZhO54AQ/8Crolddaa+z6yC1Yq5lN0hzuK/nYCC2bSzirqQ6MnPZKy
            fqyv3zq0VbG5goLCBPWKgkaYX2rt4jOnuhZrXcVOIH26nqJPYDiuhxTeEPkxzWne
            CyTn3l0mGBJy5Yq4j1i0ECFvOdVn6sr+zgXq8Tp8UnQDTmNCwcKBrLI/w1EPd/MI
            ZCUM8jFqfGK03CyIRj2Dir3i3Yd9/eIEqfiG5GwceM7RYCbxeV/G7Yby3qo9fKGw
            mIO5OyJ56tOkp+ImLdeGVWAHhrcsanMGFuVbdioXJpXtmpKUWqvwiX6Geec6jHe/
            PYu1DzqRUyzPUCkwgse/IMV9KUQCm51nAC8wl4jqOphO7/kYZaALVXCJzh0Q2RvH
            FBeoyY5CsiPKBkyuLGk0bv40r6cQPfZ2hPTWRfANhZ94QLSkhPVMxlyEl7BSY+n8
            Sq9UoOnQNsq7PB7+NtdUGmv2rWNZ/o42mFB1yatvI5kNWanCQPXxWTpw1HfJPb2+
            qH9OwHyxMEGZHX/GQEfjRl69z4IRvIxiBp+E7D/7ScT9SzlzCBskL0VvPRNKFMkG
            3Zw3ZIZkhoA/uIMNWKKP4Wb0ebQio+HhcvG05BM+8kjIW2vWkBp7fkduYaGwE5vM
            7z+FmynxpAv7tNftMLxK80EiRrYmq/eBWdxcxhAuhpW9TDza76+0H9sOH5c5z3XS
            XgEL4phOcF/tHObFY+urqyY2lB1t9AufFu8i9ZDBghloFY/sY8RBLLcUXTckbtBz
            gTdeRLomJ4T2pA0OoDZlrSX4FhCHLGdX0Fbhy3AVTxiDjfGCbYWW0GWlHzNLE2U=
            =ahOm
            -----END PGP MESSAGE-----
          fp: 57CDE9D844F97A3A7161458CD4514EB8DEB5A564
    unencrypted_suffix: _unencrypted
    version: 3.7.3
---
apiVersion: ENC[AES256_GCM,data:h+sJNkRq8kFIUYxKibr6kA7fVGBOrsTkKC/+3bk=,iv:p+XmeOxL8aqcW6rh7skF68lqT2ORy16Kroo4NKk1RZg=,tag:/PlKt48d6clt0YEfDofySQ==,type:str]
kind: ENC[AES256_GCM,data:mJlZkupDWAHnVZzlwXEoiGs=,iv:xGdCAwyXPehujE7dAfu+Q6IOt5SbekizjJ/5bWLfLgU=,tag:7rkPTqUWMT3SbBFLqlZYYg==,type:str]
metadata:
    annotations:
        tanzu.vmware.com/owner: ENC[AES256_GCM,data:MIKc,iv:Viz8f82MgOKJSqZZNFAmxgc6ns0IxCDRunK8lvhIbDA=,tag:7byE++jB5ulLkPF2kyhRwg==,type:str]
    name: ENC[AES256_GCM,data:9Yq/sqHs/tuFAMMNyPidDYGGwiJkug==,iv:0qxymV+zMntAwgP/zAwoaYAyYs12vv0xhUc4sOjJo18=,tag:m0rQZpyaubH5gEHg98GbPA==,type:str]
    namespace: ENC[AES256_GCM,data:Yy7/JEGPG4CjUnD+GMXxX7UA/g==,iv:75jbnQY5f+fXghmka8NrjDirV2X7WUn/t6MaB92w4oQ=,tag:xMd1H2iiULnhnoKhqRT5OA==,type:str]
spec:
    fetch:
        imgpkgBundle:
            image: ENC[AES256_GCM,data:bphhnFvfdnM6yXGjqfF9+RTC0RaWYSseuvwKVkDRcBf/pUGJcSmbtlO2f2jE1btqZFGI6bOjunr8+wdT0kDyosIH62YXcQD5bufKcA==,iv:/anSTOor1rPae9kU7z/T0jEk2gNdjrpR6Do8PwhjdLY=,tag:LT99Wpy1CA3VsQLtAWivMg==,type:str]
            secretRef:
                name: ENC[AES256_GCM,data:6NqRHoKAxxLJrUpl2Qcbex4X1n0=,iv:8SPKNOgnwVKIGM2JBCyGoopDcvwX6LwlmbEYbnh7p0Y=,tag:zpCgNSIquxzZQlbB00DAmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-10-19T17:34:38Z"
    mac: ENC[AES256_GCM,data:/fvRB5H4EcSOHnPA7+/FxDre2pmev1AfeNLlDeTBYF1vGtQ/4eZY6+3cd+tEZ3amzY6UGb75Sm0vccOV6OGeQsr5UJ+KcAiOLVpUoju5B/8iuQn+NDBY8ISqljEZiHlSTLmKd09pLB0YwwFUai+3sodyqYMJ1A5p0ku4gsfjv04=,iv:VDJVuEUOHWymgQ8FUqRCId0y14P0gHpAGIPQIJOAs4o=,tag:TrSP5oVI93FneJZve3cIFw==,type:str]
    pgp:
        - created_at: "2022-10-19T17:34:36Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0FQ4OXZhO54AQ/8Crolddaa+z6yC1Yq5lN0hzuK/nYCC2bSzirqQ6MnPZKy
            fqyv3zq0VbG5goLCBPWKgkaYX2rt4jOnuhZrXcVOIH26nqJPYDiuhxTeEPkxzWne
            CyTn3l0mGBJy5Yq4j1i0ECFvOdVn6sr+zgXq8Tp8UnQDTmNCwcKBrLI/w1EPd/MI
            ZCUM8jFqfGK03CyIRj2Dir3i3Yd9/eIEqfiG5GwceM7RYCbxeV/G7Yby3qo9fKGw
            mIO5OyJ56tOkp+ImLdeGVWAHhrcsanMGFuVbdioXJpXtmpKUWqvwiX6Geec6jHe/
            PYu1DzqRUyzPUCkwgse/IMV9KUQCm51nAC8wl4jqOphO7/kYZaALVXCJzh0Q2RvH
            FBeoyY5CsiPKBkyuLGk0bv40r6cQPfZ2hPTWRfANhZ94QLSkhPVMxlyEl7BSY+n8
            Sq9UoOnQNsq7PB7+NtdUGmv2rWNZ/o42mFB1yatvI5kNWanCQPXxWTpw1HfJPb2+
            qH9OwHyxMEGZHX/GQEfjRl69z4IRvIxiBp+E7D/7ScT9SzlzCBskL0VvPRNKFMkG
            3Zw3ZIZkhoA/uIMNWKKP4Wb0ebQio+HhcvG05BM+8kjIW2vWkBp7fkduYaGwE5vM
            7z+FmynxpAv7tNftMLxK80EiRrYmq/eBWdxcxhAuhpW9TDza76+0H9sOH5c5z3XS
            XgEL4phOcF/tHObFY+urqyY2lB1t9AufFu8i9ZDBghloFY/sY8RBLLcUXTckbtBz
            gTdeRLomJ4T2pA0OoDZlrSX4FhCHLGdX0Fbhy3AVTxiDjfGCbYWW0GWlHzNLE2U=
            =ahOm
            -----END PGP MESSAGE-----
          fp: 57CDE9D844F97A3A7161458CD4514EB8DEB5A564
    unencrypted_suffix: _unencrypted
    version: 3.7.3
---
apiVersion: ENC[AES256_GCM,data:URMbNaI1NKzvYOP9z+twa6ed947RhD3nHYYc6T8=,iv:Z1PJFyUcxNwWvGWMyK98R4+nkPJfe+KlGAtrQDcgJOo=,tag:hOw1yZJD0+2j8tPYJfqxww==,type:str]
kind: ENC[AES256_GCM,data:RgZH9FgtTkPpyfP3g08=,iv:fdjO3mipJBXfiXWkypm9SxaXyM6I+PA0u0IBEh53MBo=,tag:wtbHbV41SGgdMljg3iZp5Q==,type:str]
metadata:
    annotations:
        tkg.tanzu.vmware.com/tanzu-package-ClusterRole: ENC[AES256_GCM,data:pzPPnHy7j9vYXZT/GYDky6BvMKeIko9DJg==,iv:kGxZurvN6SxeOCDocqIX1oi7XIUKYTeRptFm2eeN8JM=,tag:xfEgbiGGb1vi5XO/G0Azkw==,type:str]
        tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: ENC[AES256_GCM,data:ETceXM71Uxs9K1HG+mq8r6VDGXI8ruFvXecBT06GDcQ=,iv:mppJGAzA+7EIe4QpgSKaqUyWuwpHVxZVprLcu9Wtc6o=,tag:aZZPXP42rd5icssF2gitUA==,type:str]
        tkg.tanzu.vmware.com/tanzu-package-Secret: ENC[AES256_GCM,data:Zin8qKHtpHHIoqsVRMosllPvDg==,iv:LcvRNiH3UzyLvy3GQrs2f4nqF+oGdV4XVdlOcM0AxkQ=,tag:z33PVi8rBOojfSeVau3rvg==,type:str]
        tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: ENC[AES256_GCM,data:GGylxfp+4yP7JjnWKmT0,iv:wi3xCtHERAjsY2Z9OycZlVikW5IJaMHqb3Bw5PrwgcY=,tag:mRENApCszYDeBPbKWRQ34w==,type:str]
    name: ENC[AES256_GCM,data:+v+k,iv:Q+85nopNJj5klcpn5Sci6KYjnGeFjrRSE3dwa9V/f44=,tag:YuQrPI6pOkbHUYK3rG73Kw==,type:str]
    namespace: ENC[AES256_GCM,data:Z0vKmQkIxIAGMgWYsRmxPDRixg==,iv:wJAWXNPu+zAB9IZYnQO7SazCwtT9sVw165av6Bnh5Xk=,tag:VYgrQqxN4y69PnMijF69Iw==,type:str]
spec:
    serviceAccountName: ENC[AES256_GCM,data:UO/fJwaCPmxk8o6/2DKn,iv:4Ytl9KgtlP6tFnoYTJ7d772OF//yo7P3q8s30VGhJx8=,tag:pcOlheZnnl8U5kPuHY2v+A==,type:str]
    packageRef:
        refName: ENC[AES256_GCM,data:oPf7WQ7/6QDB4GwkhdfBBNM0eUnIPMUAzD+SUOwuhZhPkJd0Bd13fYlNMes=,iv:MpXljH3rxE1e2d4vfHhpuHA+1ka5n9DXdiN6I2DnDgA=,tag:vXspnhfVpBSiX7kZN7v79g==,type:str]
        versionSelection:
            constraints: ENC[AES256_GCM,data:q8ExJg0=,iv:9053LL5l1cZb+TZq4wyvnyl+CMiuFMqrMg+IQx2Y3Sg=,tag:JHGh5d7yMHpmm8REwr9M8w==,type:str]
    values:
        - secretRef:
            name: ENC[AES256_GCM,data:0Pv+ce1vG/y8Zeikrwlzuw54cQ==,iv:9H6yoBaeRy0bUZ+MZcYqxtT6CyYeNi1jCY2DG0rXcfY=,tag:RaDAn18twC7xNt/yRHvLSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-10-19T17:34:38Z"
    mac: ENC[AES256_GCM,data:/fvRB5H4EcSOHnPA7+/FxDre2pmev1AfeNLlDeTBYF1vGtQ/4eZY6+3cd+tEZ3amzY6UGb75Sm0vccOV6OGeQsr5UJ+KcAiOLVpUoju5B/8iuQn+NDBY8ISqljEZiHlSTLmKd09pLB0YwwFUai+3sodyqYMJ1A5p0ku4gsfjv04=,iv:VDJVuEUOHWymgQ8FUqRCId0y14P0gHpAGIPQIJOAs4o=,tag:TrSP5oVI93FneJZve3cIFw==,type:str]
    pgp:
        - created_at: "2022-10-19T17:34:36Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0FQ4OXZhO54AQ/8Crolddaa+z6yC1Yq5lN0hzuK/nYCC2bSzirqQ6MnPZKy
            fqyv3zq0VbG5goLCBPWKgkaYX2rt4jOnuhZrXcVOIH26nqJPYDiuhxTeEPkxzWne
            CyTn3l0mGBJy5Yq4j1i0ECFvOdVn6sr+zgXq8Tp8UnQDTmNCwcKBrLI/w1EPd/MI
            ZCUM8jFqfGK03CyIRj2Dir3i3Yd9/eIEqfiG5GwceM7RYCbxeV/G7Yby3qo9fKGw
            mIO5OyJ56tOkp+ImLdeGVWAHhrcsanMGFuVbdioXJpXtmpKUWqvwiX6Geec6jHe/
            PYu1DzqRUyzPUCkwgse/IMV9KUQCm51nAC8wl4jqOphO7/kYZaALVXCJzh0Q2RvH
            FBeoyY5CsiPKBkyuLGk0bv40r6cQPfZ2hPTWRfANhZ94QLSkhPVMxlyEl7BSY+n8
            Sq9UoOnQNsq7PB7+NtdUGmv2rWNZ/o42mFB1yatvI5kNWanCQPXxWTpw1HfJPb2+
            qH9OwHyxMEGZHX/GQEfjRl69z4IRvIxiBp+E7D/7ScT9SzlzCBskL0VvPRNKFMkG
            3Zw3ZIZkhoA/uIMNWKKP4Wb0ebQio+HhcvG05BM+8kjIW2vWkBp7fkduYaGwE5vM
            7z+FmynxpAv7tNftMLxK80EiRrYmq/eBWdxcxhAuhpW9TDza76+0H9sOH5c5z3XS
            XgEL4phOcF/tHObFY+urqyY2lB1t9AufFu8i9ZDBghloFY/sY8RBLLcUXTckbtBz
            gTdeRLomJ4T2pA0OoDZlrSX4FhCHLGdX0Fbhy3AVTxiDjfGCbYWW0GWlHzNLE2U=
            =ahOm
            -----END PGP MESSAGE-----
          fp: 57CDE9D844F97A3A7161458CD4514EB8DEB5A564
    unencrypted_suffix: _unencrypted
    version: 3.7.3
