apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: tanzu-mysql-operator-packages-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: tanzu-mysql-operator-packages-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-Secret: tanzu-mysql-operator-packages-values
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: tanzu-mysql-operator-packages-sa
  name: tanzu-mysql-operator
  namespace: tanzu-mysql-for-kubernetes-system
spec:
  packageRef:
    refName: mysql-operator.with.sql.tanzu.vmware.com
    versionSelection:
      constraints: 1.6.1
  serviceAccountName: tanzu-mysql-operator-packages-sa
  values:
  - secretRef:
      name: tanzu-mysql-operator-packages-values
