---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: dod-cas
  namespace: tap-install
spec:
  inputResources:
    - name: dod-root-cas
      ref:
        apiVersion: v1
        kind: Secret
        name: dod-root-cas
  template:
    data:
      ca.crt: $(.dod-root-cas.data.ca\.pem)
    stringData:
      type: ca-certificates
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: dod-cas           # The name of the SecretTemplate that created the "ca-certificates" Secret.
  namespace: tap-install    # The namespace in which Tanzu Application Platform's self-signed ClusterIssuer stores its CA cert Secret.
spec:
  toNamespace: dotnet-ns        # The namespace in which Workloads are deployed.
---
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: dod-cas
  namespace: dotnet-ns            # The namespace in which Workloads are deployed.
spec:
  fromNamespace: tap-install   # The namespace in which your custom CA certificate Secret resides.