apiVersion: v1
kind: Secret
metadata:
    # `git-ssh` is the default name.
    name: github-ssh-secret
    #   - operators can change such default by using the
    #     `gitops.ssh_secret` property in `tap-values.yaml`
    #   - developers can override by using the workload parameter
    #     named `gitops_ssh_secret`.
    # namespace: tap-install
    annotations:
        # ! required
        tekton.dev/git-0: <GIT_URL> # Replace this value with your git repository URL
# ! required
type: kubernetes.io/basic-auth
stringData:
    username: # Git Username
    password: # Git Password
