---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
- tap-package-install.yaml
secretGenerator:
- name: tap-packages-values
  namespace: tap-install
  files:
  - tap-values.yaml
  type: Opaque
  options:
    annotations:
      tkg.tanzu.vmware.com/tanzu-package: tap-packages
# - name: node-extra-ca-certs
#   namespace: tap-gui
#   files:
#   - node-extra-ca-certs.yaml
#   type: Opaque
#   options:
#     annotations:
#       tkg.tanzu.vmware.com/tanzu-package: tap-packages
