apiVersion: v1
kind: Pod
metadata:
  annotations:
  name: stack-pod-debug
  namespace: default
spec:
  containers:
  - args:
    - "3600"
    command:
    - sleep
    env:
    - name: DOCKER_CONFIG
      value: /registry-secret
    image: cs-s-harbor.avmc.army.mil/tbs/1.10.11@sha256:0cd65bf4d8a8a61b8060c9b2171b35c2406fa002082a6e67bd32a658229b81e1
    imagePullPolicy: IfNotPresent
    name: create-build-image
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /workspace
      name: workspace-volume
    - mountPath: /ca-certs
      name: build-ca-certs-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-2czgv
      readOnly: true
    workingDir: /workspace
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - args:
    - /workspace/stackify
    command:
    - copybinary
    image: registry.tanzu.vmware.com/tanzu-application-platform/tap-packages@sha256:db41a2d916ebcdbe06e349609dc08d27d2fe4d2f5b7bc5a99178207f3e9759da
    imagePullPolicy: IfNotPresent
    name: copy-stackify-binary
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /workspace
      name: workspace-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-2czgv
      readOnly: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    runAsGroup: 0
    runAsUser: 0
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: workspace-volume
  - configMap:
      defaultMode: 420
      name: dod-ca-certs
    name: build-ca-certs-volume
  - configMap:
      defaultMode: 420
      name: dod-ca-certs
    name: run-ca-certs-volume
  - name: kube-api-access-2czgv
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
