apiVersion: v1
kind: Namespace
metadata:
  name: tap-install
  labels: 
    name: tap-install
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: tap-packages-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: tap-packages-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-Secret: tap-packages-values
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: tap-packages-sa
  name: tap
  namespace: tap-install
spec:
  serviceAccountName: tap-packages-sa
  packageRef:
    refName: tap.tanzu.vmware.com
    versionSelection:
      constraints: 1.2.1
  values:
  - secretRef:
      name: tap-packages-values
