apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  annotations:
    tanzu.vmware.com/owner: tkg
  name: cert-manager
  namespace: cert-manager
spec:
  fetch:
    imgpkgBundle:
      image: projects.registry.vmware.com/tkg/packages/standard/repo:v1.5.4

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: cert-manager-packages-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: cert-manager-packages-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: cert-manager-packages-sa
  name: cert-manager
  namespace: cert-manager
spec:
  serviceAccountName: cert-manager-packages-sa
  packageRef:
    refName: cert-manager.tanzu.vmware.com
    versionSelection:
      constraints: 1.5.3+vmware.2-tkg.1
